fixing coverage

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -24,8 +24,17 @@ jobs:
       run: dotnet restore ./SpellingBee/SpellingBee.csproj
     - name: Build
       run: dotnet build --no-restore ./SpellingBee/SpellingBee.csproj
+    - name: Install Coverlet
+      run:  cd TestSpellingBee && dotnet add package coverlet.msbuild
     - name: Test
-      run: dotnet test --no-build --verbosity normal ./SpellingBee/SpellingBee.csproj
+      run: dotnet test ./SpellingBee/SpellingBee.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "trx;LogFileName=test-results.trx" 
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Dotnet Tests            # Name of the check run which will be created
+        path: TestSpellingBee/TestResults/test-results.trx   # Path to test results
+        reporter: dotnet-trx        # Format of test results
     - name: Upload coverage reports to Codecov
     - name: Codecov
       uses: codecov/codecov-action@v3
